name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.1 

      - name: Install dependencies for data-collect
        run: |
          cd src/data-collect
          npm install

      - name: Install dependencies for data-retrieve
        run: |
          cd src/data-retrieve
          npm install

      - name: Install dependencies for analytical-model
        run: |
          cd src/analytical-model
          npm install

      - name: Package Lambda functions
        run: |
          cd src/data-collect
          zip -r ../../terraform/lambda-deployment-package-collect.zip .
          cd ../data-retrieve
          zip -r ../../terraform/lambda-deployment-package-retrieve.zip .
          cd ../analytical-model
          zip -r ../../terraform/lambda-deployment-package-analyse.zip .

  cd:
    runs-on: ubuntu-latest
    needs: ci  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.2  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Clean up ZIP files
        run: |
          rm terraform/lambda-deployment-package-collect.zip terraform/lambda-deployment-package-retrieve.zip terraform/lambda-deployment-package-analyse.zip