name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [data-collect, data-retrieve, analytical-model]
      max-parallel: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.1

      - name: Install dependencies
        run: cd src/${{ matrix.service }} && npm install

      - name: Run linting
        run: cd src/${{ matrix.service }} && npm run lint

      - name: Run typechecking
        run: cd src/${{ matrix.service }} && npm run typecheck

      - name: Run tests with coverage
        id: test_with_coverage
        run: |
          cd src/${{ matrix.service }}
          mkdir -p ../../test-reports
          # Run tests and capture full output
          npm run test -- --coverage > ../../test-reports/test-full-output-${{ matrix.service }}.txt || true

          # Extract just the test results and coverage summary
          cat ../../test-reports/test-full-output-${{ matrix.service }}.txt | grep -A 100 "PASS\|FAIL" | grep -B 100 "Time:" > ../../test-reports/test-report-${{ matrix.service }}.txt
          echo "" >> ../../test-reports/test-report-${{ matrix.service }}.txt
          cat ../../test-reports/test-full-output-${{ matrix.service }}.txt | grep -A 10 "Coverage summary" >> ../../test-reports/test-report-${{ matrix.service }}.txt
        continue-on-error: true

      # - name: Install dependencies
      #   run: cd src/tests/e2eTest && npm install

      # - name: Run e2e tests
      #   run: cd src/tests/e2eTest && npm run test

      # - name: Install dependencies
      #   run: cd src/tests/contractTest && npm install

      # - name: Run contract tests
      #   run: cd src/tests/contractTest && npm run test

      # Convert test output to PDF
      - name: Convert test output to PDF
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y enscript ghostscript
          enscript -p - test-reports/test-report-${{ matrix.service }}.txt | ps2pdf - test-reports/test-report-${{ matrix.service }}.pdf
        continue-on-error: true

      # Upload test report as artifact
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.service }}
          path: |
            test-reports/test-report-${{ matrix.service }}.*
          retention-days: 30
        if: always()

      # Package Lambda function
      - name: Package Lambda function
        run: |
          cd src/${{ matrix.service }}
          zip -r ../../terraform/lambda-deployment-package-${{ matrix.service }}.zip .

      # Upload as an artifact
      - name: Upload Lambda package
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package-${{ matrix.service }}
          path: terraform/lambda-deployment-package-${{ matrix.service }}.zip
          retention-days: 10

  mark-success:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Create success marker file
        run: echo "CI completed successfully" > ci-success-marker.txt

      - name: Upload CI success marker
        uses: actions/upload-artifact@v4
        with:
          name: ci-success
          path: ci-success-marker.txt
